// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdJzgFKwQteRFDjbUv0pWDwpFNi3cnOR4',
    appId: '1:122103662485:web:8d8c4cecefbe5fd128589c',
    messagingSenderId: '122103662485',
    projectId: 'islamia-org',
    authDomain: 'islamia-org.firebaseapp.com',
    databaseURL: 'https://islamia-org-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'islamia-org.firebasestorage.app',
    measurementId: 'G-TBR5VSG0CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACliLY1vnJyV7xRK9NXvecFibOmQSsErs',
    appId: '1:122103662485:android:60931ff0fd6f072628589c',
    messagingSenderId: '122103662485',
    projectId: 'islamia-org',
    databaseURL: 'https://islamia-org-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'islamia-org.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzkwbtewRDPlKXl4tV2LNcsSdkHmpc9Gc',
    appId: '1:122103662485:ios:77eb2750101e557a28589c',
    messagingSenderId: '122103662485',
    projectId: 'islamia-org',
    databaseURL: 'https://islamia-org-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'islamia-org.firebasestorage.app',
    iosBundleId: 'com.example.islamia',
  );
}
