import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Import Firebase Core
import 'package:islamia/features/home/presentation/pages/home_page.dart';
// It's good practice to have firebase_options.dart generated by FlutterFire CLI
// import 'firebase_options.dart'; // TODO: Generate this file using `flutterfire configure`

void main() async { // Make main async
  WidgetsFlutterBinding.ensureInitialized(); // Ensure Flutter bindings are initialized

  // TODO: Ensure you have configured Firebase for your project.
  // This typically involves running `flutterfire configure` which generates
  // a `firebase_options.dart` file and sets up platform-specific configurations
  // (e.g., google-services.json for Android, GoogleService-Info.plist for iOS).
  // For now, we'll initialize with default options if available (requires firebase_options.dart),
  // but a valid firebase_options.dart and platform-specific setup are crucial for full functionality.
  // If firebase_options.dart is not present, this will throw an error on some platforms
  // or use a default app if one is configured.
  await Firebase.initializeApp(
    // options: DefaultFirebaseOptions.currentPlatform, // Uncomment if firebase_options.dart is generated
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Islamia',
      theme: ThemeData(
        primarySwatch: Colors.green, // Existing theme
        // You might want to use a more specific colorScheme later:
        // colorScheme: ColorScheme.fromSeed(seedColor: Colors.green),
        // useMaterial3: true, // Consider enabling Material 3
      ),
      home: const HomePage(),
    );
  }
}
